- name: functions
  hosts: localhost
  connection: localhost
  vars:
    person: "John Doe,ramesh,suresh"
  tasks:
    - name: create-functions-deployment
      ansible.builtin.debug:
        msg: "Creating functions deployment"

    - name: create a list of functions
      ansible.builtin.debug:
        msg: "hello {{ person.split(',') }}"     

    - name: create a map to list
      vars:
       course:
          name: Ansible
          duration: 2 weeks
          name: Docker
          duration: 3 weeks
      ansible.builtin.debug:
        msg: "hello {{ course | dict2items }}"    