- name: functions
  hosts: localhost
  connection: local

  vars:
    person: "John Doe,ramesh,suresh"

    courses:
      - name: Ansible
        duration: 2 weeks

      - name: Docker
        duration: 3 weeks

      - name: Kubernetes
        duration: 4 weeks

      - name: AWS
        duration: 6 weeks

  tasks:
    - name: create-functions-deployment
      ansible.builtin.debug:
        msg: "Creating functions deployment"

    - name: create a list of functions
      ansible.builtin.debug:
        msg: "hello {{ person.split(',') }}"

    - name: display courses
      ansible.builtin.debug:
        msg: "{{ courses }}"